name: Package Build and Test

on:
  workflow_call:
    inputs:
      GIT_TAG:
        required: true
        type: string
      BUILD_DATE:
        required: true
        type: string
      ARCH:
        required: true
        type: string

jobs:
  package-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential dpkg-dev gpg tree

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download sys_info build
        uses: actions/download-artifact@v4
        with:
          name: sys-info

      - name: Set binary location
        run: |
          mkdir -p pkg/sys-info_"${{ inputs.GIT_TAG }}"-"${{ inputs.BUILD_DATE }}"_"${{ inputs.ARCH }}"/usr/bin
          cp -r sys-info pkg/sys-info_"${{ inputs.GIT_TAG }}"-"${{ inputs.BUILD_DATE }}"_"${{ inputs.ARCH }}"/usr/bin
          sudo chmod 755 pkg/sys-info_"${{ inputs.GIT_TAG }}"-"${{ inputs.BUILD_DATE }}"_"${{ inputs.ARCH }}"/usr/bin/sys-info
          tree

      - name: DEBIAN control and postinst files
        run: |
          # Debian package structure
          mkdir -p pkg/sys-info_"${{ inputs.GIT_TAG }}"-"${{ inputs.BUILD_DATE }}"_"${{ inputs.ARCH }}"/DEBIAN
          cp pkg/scripts/control  pkg/sys-info_"${{ inputs.GIT_TAG }}"-"${{ inputs.BUILD_DATE }}"_"${{ inputs.ARCH }}"/DEBIAN/control
          sed -i "s/<VERSION>/"${{ inputs.GIT_TAG }}"-"${{ inputs.BUILD_DATE }}"/g" pkg/sys-info_"${{ inputs.GIT_TAG }}"-"${{ inputs.BUILD_DATE }}"_"${{ inputs.ARCH }}"/DEBIAN/control
          sed -i "s/<ARCH>/"${{ inputs.ARCH }}"/g" pkg/sys-info_"${{ inputs.GIT_TAG }}"-"${{ inputs.BUILD_DATE }}"_"${{ inputs.ARCH }}"/DEBIAN/control

          # Pre installation script
          cp pkg/scripts/preinst pkg/sys-info_"${{ inputs.GIT_TAG }}"-"${{ inputs.BUILD_DATE }}"_"${{ inputs.ARCH }}"/DEBIAN/preinst
          chmod 755 pkg/sys-info_"${{ inputs.GIT_TAG }}"-"${{ inputs.BUILD_DATE }}"_"${{ inputs.ARCH }}"/DEBIAN/preinst

          # Post installation script
          cp pkg/scripts/postinst pkg/sys-info_"${{ inputs.GIT_TAG }}"-"${{ inputs.BUILD_DATE }}"_"${{ inputs.ARCH }}"/DEBIAN/postinst
          chmod 755 pkg/sys-info_"${{ inputs.GIT_TAG }}"-"${{ inputs.BUILD_DATE }}"_"${{ inputs.ARCH }}"/DEBIAN/postinst

          # Pre Removal script
          cp pkg/scripts/prerm pkg/sys-info_"${{ inputs.GIT_TAG }}"-"${{ inputs.BUILD_DATE }}"_"${{ inputs.ARCH }}"/DEBIAN/prerm
          chmod 755 pkg/sys-info_"${{ inputs.GIT_TAG }}"-"${{ inputs.BUILD_DATE }}"_"${{ inputs.ARCH }}"/DEBIAN/prerm

          # Post Removal script
          cp pkg/scripts/postrm pkg/sys-info_"${{ inputs.GIT_TAG }}"-"${{ inputs.BUILD_DATE }}"_"${{ inputs.ARCH }}"/DEBIAN/postrm
          chmod 755 pkg/sys-info_"${{ inputs.GIT_TAG }}"-"${{ inputs.BUILD_DATE }}"_"${{ inputs.ARCH }}"/DEBIAN/postrm

      - name: Build DEB package
        run: |
          cd pkg
          dpkg --build sys-info_"${{ inputs.GIT_TAG }}"-"${{ inputs.BUILD_DATE }}"_"${{ inputs.ARCH }}"

      - name: relocate artifact
        run: |
          mv pkg/sys-info_"${{ inputs.GIT_TAG }}"-"${{ inputs.BUILD_DATE }}"_"${{ inputs.ARCH }}".deb sys-info.deb
          ls -la sys-info.deb

      - name: Debian Package artifact
        uses: actions/upload-artifact@v4
        with:
          name: sys-info.deb
          path: sys-info.deb
          retention-days: 5
