name: Package Build and Test

on:
  workflow_call:

jobs:
  package-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential dpkg-dev gpg tree

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download sys_info build
        uses: actions/download-artifact@v4
        with:
          name: sys-info

      - name: Remove package
        run: ls -la
