name: Automatic Version Bumper
on:
  workflow_dispatch:
  schedule:
    - cron: "2 2 * * 2"       # Weekly: Increment patch version
    - cron: "2 2 2 * *"       # Monthly: Increment minor version
    - cron: "2 2 2 */2 *"     # Bi-monthly: Increment major version

jobs:
  bump-version:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.PAT }}" | gh auth login --with-token
      - name: Get current version
        id: version
        run: |
          CURRENT_VERSION=$(awk 'NF {print; exit}' VERSION)

          echo "CURRENT_VERSION=$CURRENT_VERSION"
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
      - name: Calculate new Patch
        # if: (github.event.schedule == '2 2 * * *' || github.event_name == 'workflow_dispatch')
        run: |
          echo "CURRENT_VERSION: $CURRENT_VERSION"

          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          PATCH=$((PATCH + 1))
          NEW_VERSION="Version: ${MAJOR}.${MINOR}.${PATCH}"

          echo "NEW_VERSION=$NEW_VERSION" >>$GITHUB_ENV
          echo "NEW_VERSION=$NEW_VERSION"

          echo "VERSION=${MAJOR}.${MINOR}.${PATCH}" >>$GITHUB_ENV
          echo "VERSION=${MAJOR}.${MINOR}.${PATCH}"
      - name: Calculate new Minor
        if: github.event.schedule == '2 2 2 * *'
        run: |
          echo "CURRENT_VERSION: $CURRENT_VERSION"

          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          MINOR=$((MINOR + 1))
          PATCH=0
          NEW_VERSION="Version: ${MAJOR}.${MINOR}.${PATCH}"

          echo "NEW_VERSION=$NEW_VERSION" >>$GITHUB_ENV
          echo "NEW_VERSION=$NEW_VERSION"

          echo "VERSION=${MAJOR}.${MINOR}.${PATCH}" >>$GITHUB_ENV
          echo "VERSION=${MAJOR}.${MINOR}.${PATCH}"
      - name: Calculate new Major
        if: github.event.schedule == '2 2 2 */2 *'
        run: |
          echo "CURRENT_VERSION: $CURRENT_VERSION"

          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          MAJOR=$((MAJOR + 1))
          MINOR=0
          PATCH=0
          NEW_VERSION="Version: ${MAJOR}.${MINOR}.${PATCH}"

          echo "NEW_VERSION=$NEW_VERSION" >>$GITHUB_ENV
          echo "NEW_VERSION=$NEW_VERSION"

          echo "VERSION=${MAJOR}.${MINOR}.${PATCH}" >>$GITHUB_ENV
          echo "VERSION=${MAJOR}.${MINOR}.${PATCH}"
      - name: Set new version
        run: |
          sed -i "s/^\(.*Version:.*\)$/  printf(\"${NEW_VERSION}\");/" src/sys-info.c
          echo "${VERSION}" >VERSION
      - name: Push changes
        run: |
          git add .
          git commit -m "Upgrading version to: $VERSION from $CURRENT_VERSION"
          git tag "$VERSION" -m "Bump to $VERSION"
      - name: Push
        run: |
          git push origin main
          git push origin --tags

  test-code:
    needs: bump-version
    uses: ./.github/workflows/build.yml
    secrets: inherit
