name: Automatic Version Bumper

on:
  schedule:
    - cron: "2 2 * * *"
    - cron: "2 2 2 * *"
    - cron: "2 2 2 */2 *"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate GitHub CLI
        run: |
          git config user.name "aasanchez"
          git config user.email "aasanchez@gmail.com"
          echo "${{ secrets.PAT }}" | gh auth login --with-token

      - name: Get latest tag
        run: |
          git fetch --tags
          GIT_TAG=$(git tag -l | grep -E "^[0-9]+\.[0-9]+\.[0-9]+$" | sort -V | tail -n 1)
          echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV

      - name: Calculate new Patch
        if: github.event.schedule == '2 2 * * *'
        run: |
          IFS='.' read -r MAJOR MINOR PATCH <<< "$GIT_TAG"
          PATCH=$((PATCH + 1))
          # Build the new version string
          NEW_VERSION="Version: ${MAJOR}.${MINOR}.${PATCH}"
          echo "NEW_VERSION=$NEW_VERSION" >>$GITHUB_ENV
          echo "VERSION=${MAJOR}.${MINOR}.${PATCH}" >>$GITHUB_ENV

      - name: Calculate new Minor
        if: github.event.schedule == '2 2 2 * *'
        run: |
          IFS='.' read -r MAJOR MINOR PATCH <<< "$GIT_TAG"
          MINOR=$((MINOR + 1))
          # Build the new version string
          NEW_VERSION="Version: ${MAJOR}.${MINOR}.0"
          echo "NEW_VERSION=$NEW_VERSION" >>$GITHUB_ENV
          echo "VERSION=${MAJOR}.${MINOR}.0" >>$GITHUB_ENV

      - name: Calculate new Major
        if: github.event.schedule == '2 2 2 */2 *'
        run: |
          IFS='.' read -r MAJOR MINOR PATCH <<< "$GIT_TAG"
          MAJOR=$((MAJOR + 1))
          # Build the new version string
          NEW_VERSION="Version: ${MAJOR}.0.0"
          echo "NEW_VERSION=$NEW_VERSION" >>$GITHUB_ENV
          echo "VERSION=${MAJOR}.0.0" >>$GITHUB_ENV

      - name: Set new version
        run: |
          sed -i "s/^\(.*Version:.*\)$/  printf(\"${NEW_VERSION}\");/" src/sys-info.c
          git add .
          git commit -m "Upgrading version to: $VERSION"
          git tag "$VERSION" -m "Bump to $VERSION"

      - name: Push
        run: |
          git push origin master
          git push origin --tags
